- defaults:
    link:
        relink: true
        create: true

- sudo:
    - aptget:
        codium:
        zathura:
        qutebrowser:
- shell:
    - rm ~/.dotfiles/meta/plugins/dotbot-sudo/sudo.conf.json

- link:
    ~/.inputrc: rc/.inputrc
    ~/.xprofile: rc/.xprofile
    ~/.config/alacritty: alacritty
    ~/.config/VSCodium: vscodium
    ~/.config/zathura: zathura
    ~/.xmodmap: x/.xmodmap
    ~/.local/share/applications/firefox-private.desktop: desktop/firefox-private.desktop
    ~/.config/qutebrowser: browser/qutebrowser
    ~/.local/share/qutebrowser/greasemonkey: browser/userscripts
    ~/.local/share/pop-launcher: pop-launcher

- shell:
    - codium --install-extension DivyanshuAgrawal.competitive-programming-helper
    - codium --install-extension formulahendry.code-runner
    - codium --install-extension yzhang.markdown-all-in-one
    - codium --install-extension cweijan.vscode-office
    - codium --install-extension asvetliakov.vscode-neovim
