- sudo:
    - shell:
        -  curl -fsSL https://get.casaos.io | bash 
        - sudo docker pull portainer/portainer-ce:latest
        - sudo docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
        - wget -qO- https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/tools/rpi_docker_monitor.sh | bash
        - curl -fsSL https://tailscale.com/install.sh | sh
        - tailscale up
    - aptget:
        shellinabox:
