- defaults:
    link:
        relink: true
        create: true

- sudo:
    - aptget:
        zsh:
        neovim:
            ppa_source: ppa:neovim-ppa/unstable
            upgrade: true
        tmux:
        neofetch:
        fzf:
        fd-find:
        bat:
        pass:
        neomutt:
        gnupg:
    - shell:
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile default --no-modify-path
- shell:
    - rm ~/.dotfiles/meta/plugins/dotbot-sudo/sudo.conf.json

- pip:
    file: python/requirements.txt
    stdout: false
    stderr: true

- cargo:
    - tealdeer
    - rm-improved
- shell:
    - export PATH="$HOME/.cargo/bin:$PATH"
    - tldr --update

- link:
    ~/.hushlogin: rc/.hushlogin
    ~/.dircolors: rc/.dircolors
    ~/.bashrc: bash/.bashrc
    ~/.zshrc: zsh/.zshrc
    ~/.config/neofetch: neofetch 
    ~/.config/nvim: nvim
    ~/.mutt: mutt
    ~/.vim: vim
    ~/.config/ranger: ranger
    ~/.config/pistol: pistol
    ~/.config/bat: bat
    ~/.tmux.conf: tmux/.tmux.conf
    ~/.tmux.conf: tmux/.tmux.conf

- ifaarch64:
    - shell:
        - wget -O ~/.local/bin/pistol https://github.com/doronbehar/pistol/releases/latest/download/pistol-static-aarch64
    - shell:
        - wget -O ~/.local/bin/pistol https://github.com/doronbehar/pistol/releases/latest/download/pistol-static-armv7l
    - shell:
        - wget -O ~/.local/bin/pistol https://github.com/doronbehar/pistol/releases/latest/download/pistol-static-x86_64

- shell:
    - chsh -s $(which zsh)
    - sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" "" --unattended
    - mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
    - mkdir -p ~/.local/bin

- git:
    '~/.oh-my-zsh/plugins/zsh-autosuggestions':
        url: 'https://github.com/zsh-users/zsh-autosuggestions'
    '~/.oh-my-zsh/plugins/zsh-syntax-highlighting':
        url: 'https://github.com/zsh-users/zsh-syntax-highlighting'
