[window]
decorations = "none"

[colors.cursor]
cursor = "#528bff"
text = "CellBackground"

[colors.normal]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828997"
yellow = "#e5c07b"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font.normal]
family = "Caskaydia Cove Nerd Font Mono"

[shell]
program = "/usr/bin/tmux"
args = ["new-session"]
