" Import settings, plugins, themes etc from different files
" source ./settings/file.vim

" General customization
runtime ./settings/settings.vim
runtime ./settings/plugins.vim
runtime ./settings/themes.vim
runtime ./settings/keybindings.vim
runtime ./settings/nerdtree.vim
runtime ./settings/barbar.vim
runtime ./settings/vim-airline.vim
